import { VERT, FRAG, SEGMENTS } from '../engine/beam.js';
import { burstEnvelope, smoothstep } from '../engine/lifecycle.js';

/**
 * Method export.
 *
 * A preset is only reproducible if you can rebuild the effect somewhere else.
 * Numbers alone don't do that, so every export emits three artifacts:
 *
 *   <name>.json       the parameters
 *   <name>.beam.js    a self-contained drop-in module (three.js the only dep)
 *   <name>.recipe.md  the technique in prose, with these numbers in it
 */

const uniformName = (key) => 'u' + key[0].toUpperCase() + key.slice(1);

/** Beam params only — scene/camera settings aren't part of the effect. */
const SCENE_KEYS = new Set(['bgBrightness', 'exposure']);

export function splitState(state){
  const beam = {}, scene = {};
  for (const [k, v] of Object.entries(state)) (SCENE_KEYS.has(k) ? scene : beam)[k] = v;
  return { beam, scene };
}

// --- 1. parameters --------------------------------------------------------

export function buildJson(state, name){
  const { beam, scene } = splitState(state);
  return JSON.stringify({
    schema: 'laserfx/1',
    id: name,
    generator: 'lab-satisfying-lasers',
    generatedAt: new Date().toISOString(),
    beam,
    scene,
  }, null, 2) + '\n';
}

// --- 2. drop-in module ----------------------------------------------------

/** Escape a GLSL source so it can sit inside a generated template literal. */
const escapeTemplate = (src) => src.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

export function buildModule(state, name){
  const { beam } = splitState(state);
  // Embed the live source of the envelope so the export can never drift
  // from the behaviour you just tuned in the lab.
  const BURST_SRC = [smoothstep.toString(), burstEnvelope.toString()].join('\n\n');
  const defaults = Object.entries(beam)
    .map(([k, v]) => `  ${k}: ${typeof v === 'string' ? JSON.stringify(v) : v},`)
    .join('\n');

  return `// ${name}.beam.js — generated by lab-satisfying-lasers
// A camera-facing ribbon laser. Only dependency is three.js.
//
//   import { createBeam } from './${name}.beam.js';
//   const laser = createBeam(new THREE.Vector3(-3, 1, 0), new THREE.Vector3(3, 1, 0));
//   scene.add(laser.mesh);
//   // in your loop:
//   laser.update(clock.getElapsedTime());
//
// Override any parameter: createBeam(a, b, { glowColor: '#22ddff' })

import * as THREE from 'three';

export const SEGMENTS = ${SEGMENTS};

export const DEFAULTS = {
${defaults}
};

const VERT = \`${escapeTemplate(VERT)}\`;

const FRAG = \`${escapeTemplate(FRAG)}\`;

function buildGeometry(){
  const vertCount = (SEGMENTS + 1) * 2;
  const position = new Float32Array(vertCount * 3); // written by the vertex shader
  const aU = new Float32Array(vertCount);
  const aV = new Float32Array(vertCount);
  const index = new Uint16Array(SEGMENTS * 6);

  for (let i = 0; i <= SEGMENTS; i++){
    const u = i / SEGMENTS;
    aU[i * 2] = u;      aV[i * 2] = -1;
    aU[i * 2 + 1] = u;  aV[i * 2 + 1] = 1;
  }
  for (let i = 0; i < SEGMENTS; i++){
    const a = i * 2, b = a + 1, c = a + 2, d = a + 3;
    index.set([a, c, b, b, c, d], i * 6);
  }

  const g = new THREE.BufferGeometry();
  g.setAttribute('position', new THREE.BufferAttribute(position, 3));
  g.setAttribute('aU', new THREE.BufferAttribute(aU, 1));
  g.setAttribute('aV', new THREE.BufferAttribute(aV, 1));
  g.setIndex(new THREE.BufferAttribute(index, 1));
  return g;
}

const COLOR_KEYS = ['coreColor', 'glowColor'];
// Burst params drive the envelope on the CPU; they are not shader uniforms.
const BURST_KEYS = ['burstRate', 'burstDuty', 'burstDecay', 'burstAttack'];

${BURST_SRC}

export function createBeam(start, end, overrides = {}){
  const p = { ...DEFAULTS, ...overrides };

  const uniforms = {
    uStart: { value: start.clone() },
    uEnd:   { value: end.clone() },
    uTime:  { value: 0 },
    uAlpha: { value: 1 },
  };
  for (const [k, v] of Object.entries(p)){
    if (BURST_KEYS.includes(k)) continue;
    uniforms['u' + k[0].toUpperCase() + k.slice(1)] =
      { value: COLOR_KEYS.includes(k) ? new THREE.Color(v) : v };
  }

  const material = new THREE.ShaderMaterial({
    uniforms,
    vertexShader: VERT,
    fragmentShader: FRAG,
    transparent: true,
    blending: THREE.AdditiveBlending, // glBlendFunc(GL_SRC_ALPHA, GL_ONE)
    depthWrite: false,
    side: THREE.DoubleSide,
  });

  const mesh = new THREE.Mesh(buildGeometry(), material);
  mesh.frustumCulled = false; // positions live in the vertex shader
  mesh.renderOrder = 10;

  return {
    mesh,
    uniforms,
    update(elapsed){
      uniforms.uTime.value = elapsed;
      uniforms.uAlpha.value = burstEnvelope(elapsed, p);
    },
    setEndpoints(a, b){ uniforms.uStart.value.copy(a); uniforms.uEnd.value.copy(b); },
    setAlpha(a){ uniforms.uAlpha.value = a; },
  };
}
`;
}

// --- 3. the recipe --------------------------------------------------------

const n = (v, d = 3) => (typeof v === 'number' ? Number(v.toFixed(d)) : v);

export function buildRecipe(state, name){
  const s = state;
  return `# ${name} — recipe

Generated by lab-satisfying-lasers. This is the *method*, not just the numbers:
enough to rebuild the effect from scratch in another engine.

## 1. Geometry — a camera-facing ribbon

One quad strip of ${SEGMENTS} segments spanning emitter → target. No cylinder,
no sprites. Two attributes carry beam space:

| attr | range | meaning |
|------|-------|---------|
| \`aU\` | 0 → 1  | along the beam |
| \`aV\` | −1 → 1 | across it; ±1 sits at \`glowWidth\` |

Positions are computed in the vertex shader, so the mesh must set
\`frustumCulled = false\`. Each vertex billboards itself:

    dir  = normalize(end - start)
    p    = mix(start, end, aU)
    side = normalize(cross(dir, normalize(cameraPos - p)))
    p   += side * aV * glowWidth

Because \`side\` is rebuilt per vertex, the ribbon presents its face to the
camera from every angle without any CPU work.

## 2. Layers — analytic, not sprites

The classic recipe (jvm-gaming, 2011) stacks 7 sprites: start/mid/end caps ×
glow/core. We derive the same layering from \`aU\`/\`aV\` in one fragment shader,
which is what keeps a preset pure JSON with no textures to ship beside it.

    glow = pow(1 - |v|, ${n(s.glowFalloff, 2)})      → colored halo
    core = smoothstep band on |v|            → white-hot centre

Glow ${s.glowColor} at intensity ${n(s.glowIntensity, 2)}, core ${s.coreColor} at ${n(s.coreIntensity, 2)}.
Core width ${n(s.coreWidth)} against glow width ${n(s.glowWidth)} — roughly a ${n(s.coreWidth / s.glowWidth * 100, 0)}% ratio.
The colored-glow-plus-white-core pairing is what reads as *hot*: the eye takes
a blown-out white centre as "too bright to have a color".

## 3. Caps — taper the profile, never just the alpha

The one non-obvious trick here. Fading alpha along the length leaves a
guillotined rectangle. Instead, shrink the *width*:

    capA  = smoothstep(0, ${n(s.capStart)}, u)
    capB  = 1 - smoothstep(1 - ${n(s.capEnd)}, 1, u)
    taper = min(capA, capB)
    vT    = v / max(taper, 1e-3)     ← then run the profile on vT

Dividing the across-coordinate by the taper pinches the beam to a point at
each end. Set \`capStart\` to 0 for a beam that emerges flat from a nozzle.

## 4. Nozzle blast

    blast = exp(-u * 22) * ${n(s.blast, 2)} * pow(1 - |v|, 1.4)

The \`pow(1 - |v|, 1.4)\` matters: without an across-profile of its own, the
blast paints the full ribbon width and the beam starts as a rectangle.

## 5. Interference — the difference between alive and dead

A static line reads as a prop. Scroll 4-octave value-noise along the beam:

    n      = fbm(vec2(u * ${n(s.noiseScale, 1)} - t * ${n(s.scrollSpeed, 2)}, v * 1.5 + 4))
    interf = mix(1, n * 1.7, ${n(s.noiseAmount, 2)})

Negative \`scrollSpeed\` runs the flow back toward the emitter — reads as a
charging or draining beam rather than a firing one.
Flicker (${n(s.flicker, 2)}) is a separate cheap global multiplier.

## 6. Instability

Lateral vertex displacement, anchored at both ends by \`sin(u * π)\` so the beam
stays welded to the nozzle and the impact point however hard it shakes:

    amount ${n(s.jitterAmount)} · frequency ${n(s.jitterFreq, 0)}

## 7. Bursts

Firing is an envelope over alpha, computed per frame on the CPU:

    rate ${n(s.burstRate, 2)} /s · duty ${n(s.burstDuty, 2)} · decay ${n(s.burstDecay, 2)} · attack ${n(s.burstAttack, 3)}

    phase = (t * rate) mod 1
    if phase >= duty  ->  0            ← the gap between shots
    x     = phase / duty               ← 0..1 across one shot
    alpha = smoothstep(0, attack, x) * (1 - x^decay)

\`rate\` is the blasting speed; \`duty\` is how much of each cycle is firing, so
low duty gives short punchy shots and high duty gives a near-continuous stream.
Set \`rate\` to 0 for an uninterrupted beam.

The shaping matters more than the on/off. A square wave reads as a strobe; the
fast attack plus \`1 - x^decay\` falloff is what reads as discharges. Time keeps
advancing through the gaps, so the interference noise lands differently on each
shot and no two blasts look identical.

## 8. Blending and tone mapping

Additive — \`GL_SRC_ALPHA, GL_ONE\`, \`THREE.AdditiveBlending\` — with
\`depthWrite: false\` so overlapping beams accumulate instead of z-fighting.

Render with ACES filmic tone mapping (exposure ${n(s.exposure, 2)}). Intensities above
1.0 then roll off into white at the core while the fringe keeps its hue, which
is most of the plasma look. Without tone mapping the same values just clip flat.

Contrast is a scene property, not a beam property: these read as powerful
because the stage sits near black (background lightness ${n(s.bgBrightness, 3)}). The same
beam on a bright background looks like a colored stick.

## Parameters

\`\`\`json
${JSON.stringify(splitState(state).beam, null, 2)}
\`\`\`
`;
}

// --- download -------------------------------------------------------------

export function download(filename, text, mime = 'text/plain'){
  const url = URL.createObjectURL(new Blob([text], { type: mime + ';charset=utf-8' }));
  const a = Object.assign(document.createElement('a'), { href: url, download: filename });
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
